#! /bin/sh
export CNAME; CNAME=org.glassfish.gmbal.tools.file.CopyrightProcessor 
export ARGS
ARGS="-validate false"
ARGS="${ARGS} -verbose 1"
ARGS="${ARGS} -dryrun false"
ARGS="${ARGS} -roots ../copyrightTest"
ARGS="${ARGS} -skipdirs ARCHIVE,legal,build,dist,lib,nbproject,make,javadoc,.hg"
ARGS="${ARGS} -copyright legal/header-template.txt "
ARGS="${ARGS} -startyear 2008"
java -classpath dist/gmbal.jar ${CNAME} ${ARGS}
