#! /bin/sh
export CNAME; set CNAME=org.glassfish.gmbal.tools.file.CopyrightProcessor 
export ARGS
set ARGS = -validate false 
set ARGS = ${ARGS} -verbose true
set ARGS = ${ARGS} -dryrun true
set ARGS = ${ARGS} -roots .
set ARGS = ${ARGS} -skipdirs ARCHIVE,LEGAL,build,dist,lib,nbproject,make,gmbal 
set ARGS = ${ARGS} -copyright legal/header-template.txt 
set ARGS = ${ARGS} -startyear 2008
echo "ARGS=" ${ARGS}
#java -classpath dist/gmbal.jar ${CNAME} ${ARGS}
